version: "3"
services:
  screeps:
    platform: linux/x86_64
    image: ghcr.io/jomik/screeps-server:edge
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:
